/**
 * All user-visible copy lives here (labels.md) — components and hooks reference
 * `LABELS.*`, never a literal string, so a copy edit can't silently break a branch
 * that happens to compare against the old text.
 */
export const LABELS = {
  errors: {
    generic: 'Something went wrong. Please try again.',
  },
  auth: {
    logIn: 'Log in',
    logOut: 'Log out',
    createAccount: 'Create account',
    register: 'Register',
    noAccountPrompt: "Don't have an account?",
    hasAccountPrompt: 'Already have an account?',
    passwordShow: 'Show',
    passwordHide: 'Hide',
    passwordMinLengthHint: 'At least 8 characters.',
    emailAlreadyExists: 'An account with this email already exists.',
    tooManyAttempts: (retryAfterSeconds: unknown) =>
      `Too many attempts. Try again in ${retryAfterSeconds ?? 'a few'} seconds.`,
  },
  incidents: {
    submitReport: 'Submit report',
    viewIncident: 'View incident',
    reportAnother: 'Report another incident',
    incidentReported: 'Incident reported',
    notFoundTitle: 'Incident not found',
    notFoundBody: 'It may have been removed, or the link is incorrect.',
    backToList: 'Back to incident list',
    loadDetailError: 'Could not load this incident.',
    loadFormError: 'Could not load the report form.',
    reportPageTitle: 'Report Incident',
    reportTitle: 'Report an incident',
    reportDescription: 'Fill in what you know — invalid input is rejected before it reaches anyone.',
    listTitle: 'Incidents',
    listDescription: 'Showing incidents at or below your clearance level.',
    loadListError: 'Could not load incidents.',
    myReportsTitle: 'My reports',
    myReportsDescription:
      "Incidents you reported that you can still see — a report filed above your clearance won't appear here (Q9).",
    loadMyReportsError: 'Could not load your reports.',
    noReportsYetTitle: 'No reports yet',
    noReportsYetBody: 'Incidents you file will show up here, as long as you can still see them.',
    clearanceHidesEverythingTitle: 'Your clearance hides everything here',
    clearanceHidesEverythingBody:
      'Every incident matching these filters is above your clearance level. An investigator or manager with higher clearance can still act on them.',
    noMatchTitle: 'No incidents match these filters',
    noMatchBody: 'Try widening the date range or clearing a filter.',
    clearAllFilters: 'Clear all filters',
    noIncidentsYetTitle: 'No incidents yet',
    noIncidentsYetBody: "Reports will show up here once they're filed.",
    aboveClearanceWarning: 'Above your clearance — you may not be able to view this report afterwards.',
    severityHelp: {
      LOW: 'Routine — visible to any staff member.',
      MEDIUM: 'Elevated — visible from clearance 2 up.',
      HIGH: 'Serious — starts the escalation clock; visible from clearance 3 up.',
      CRITICAL: 'Most severe — starts the escalation clock; visible to clearance 4 only.',
    },
    columns: {
      reference: 'Reference',
      title: 'Title',
      type: 'Type',
      severity: 'Severity',
      stage: 'Stage',
      assignee: 'Assignee',
      age: 'Age',
    },
  },
  triage: {
    queueTitle: 'Triage queue',
    queueDescription: 'Unacknowledged and new incidents at or below your clearance, most escalated first.',
    loadQueueError: 'Could not load the triage queue.',
    queueEmptyTitle: 'Nothing waiting on triage',
    queueEmptyBody: 'Every incident you can see is either acknowledged or past the triage stage.',
    viewFullList: 'View the full incident list',
    triageAction: 'Move to triage',
    acknowledge: 'Acknowledge',
    acknowledged: 'Acknowledged',
    changeSeverity: 'Change severity',
    assign: 'Assign investigator',
    reassign: 'Reassign investigator',
    unassign: 'Unassign',
    changeSeverityModalTitle: 'Change severity',
    reasonLabel: 'Reason',
    reasonHint: 'At least 10 characters — this is recorded on the incident’s audit trail.',
    assignDrawerTitle: 'Assign investigator',
    noEligibleInvestigators: (minClearance: number) => `No investigator has clearance ${minClearance} or above.`,
    hiddenInvestigatorsFootnote: (hidden: number) =>
      hidden === 1
        ? '1 investigator is hidden — their clearance is below this incident’s severity.'
        : `${hidden} investigators are hidden — their clearance is below this incident’s severity.`,
    unassignConfirmTitle: 'Unassign investigator?',
    unassignConfirmBody: 'This returns the incident to Triage. The investigator keeps no further access to it.',
    triagedToast: 'Moved to triage.',
    severityChangedToast: 'Severity updated.',
    assignedToast: 'Investigator assigned.',
    unassignedToast: 'Investigator unassigned.',
    acknowledgedToast: 'Incident acknowledged.',
    selfInflictedRaiseToast: 'Severity updated — you may lose access to this incident.',
    staleVersionError: 'This incident changed while you were viewing it. Refreshing…',
  },
  investigation: {
    myInvestigationsTitle: 'My investigations',
    myInvestigationsDescription: 'Incidents assigned to you that you can still see.',
    loadMyInvestigationsError: 'Could not load your investigations.',
    noInvestigationsTitle: 'No investigations assigned',
    noInvestigationsBody: 'Incidents assigned to you will show up here.',
    notesTab: 'Notes',
    confidentialityBanner: 'Visible only to you and administrators.',
    noNotesYetTitle: 'No investigation notes yet',
    noNotesYetBody: 'Notes you and other investigators add will appear here, newest first.',
    loadNotesError: 'Could not load investigation notes.',
    loadMoreNotes: 'Load more notes',
    composerLabel: 'Add a note',
    composerPlaceholder: 'Record what you found, who you spoke to, or what happens next…',
    composerCharacterCount: (count: number, max: number) => `${count} / ${max}`,
    addNote: 'Add note',
    addNoteToast: 'Note added.',
    restrictedClearanceTitle: 'Notes require higher clearance',
    restrictedClearanceBody: 'Your clearance no longer covers this incident, so its investigation notes are hidden too.',
    restrictedNotAssignedTitle: 'Notes are limited to the assigned investigator',
    restrictedNotAssignedBody:
      'Only the assigned investigator and administrators can read or add investigation notes — a triage role alone is not enough.',
    notesClosedNotice: 'This incident is closed. Notes can no longer be added, but existing notes are preserved above.',
  },
  closure: {
    closureTab: 'Closure',
    requirementsHint: 'At least 20 characters each — this is what stops closure through the API, not just this form.',
    rootCauseLabel: 'Root cause',
    rootCausePlaceholder: 'What actually caused this incident?',
    correctiveActionLabel: 'Corrective action',
    correctiveActionPlaceholder: 'What was done, or will be done, to prevent a recurrence?',
    proposeAction: 'Propose closure',
    proposeConfirmTitle: 'Propose closure?',
    proposeConfirmBody: 'This moves the incident to Pending Closure for a manager to review.',
    proposedToast: 'Closure proposed — awaiting manager review.',
    reviewTitle: 'Closure review',
    reviewDescription: 'Read the proposed root cause and corrective action, then approve or request changes.',
    approveAction: 'Approve',
    approveConfirmTitle: 'Approve closure?',
    approveConfirmBody: 'This closes the incident. A closed incident cannot be reopened or modified.',
    approvedToast: 'Incident closed.',
    requestChangesAction: 'Request changes',
    rejectModalTitle: 'Request changes',
    rejectReasonLabel: 'What needs to change?',
    rejectReasonHint: 'At least 10 characters — this is recorded on the incident’s audit trail and shown to the investigator.',
    rejectedToast: 'Sent back for changes.',
    closedBanner: (closedAt: string, closedBy: string) => `Closed on ${closedAt} by ${closedBy}`,
    pendingQueueTitle: 'Pending closures',
    pendingQueueDescription: 'Proposed closures awaiting your approval, at or below your clearance.',
    loadPendingQueueError: 'Could not load pending closures.',
    pendingQueueEmptyTitle: 'Nothing awaiting closure review',
    pendingQueueEmptyBody: 'Proposed closures you can see will show up here.',
  },
  nav: {
    appTitle: 'Incident Reporting & Escalation',
    backToHome: 'Back to home',
  },
  feedback: {
    forbiddenTitle: "You don't have access to this page",
    forbiddenBody: "Your role doesn't permit this action. If you think this is a mistake, contact an administrator.",
    accessRevokedTitle: 'You no longer have access to this incident',
    accessRevokedBody:
      'Its severity was raised above your clearance level. This is expected — clearance is re-checked on every request.',
    comingSoonTitle: 'Not built yet',
    comingSoonBody: 'This screen lands with its feature module.',
    unexpectedErrorTitle: 'Something went wrong',
    unexpectedErrorBody: 'The application hit an unexpected error. Reloading the page usually resolves it.',
    reload: 'Reload',
  },
  escalations: {
    feedTitle: 'Escalations',
    feedDescription: 'Unacknowledged incidents past a tier threshold, most severe and longest-overdue first.',
    loadFeedError: 'Could not load the escalation feed.',
    feedEmptyTitle: 'Nothing currently escalated',
    feedEmptyBody: 'Every unacknowledged HIGH/CRITICAL incident within your clearance is caught up. Here is what triggers an escalation:',
    tiersLoadError: 'Could not load escalation tiers.',
    acknowledgeAction: 'Acknowledge',
    acknowledgedToast: 'Acknowledged — removed from the feed.',
    historyTitle: 'Escalation history',
    historyLoadError: 'Could not load escalation history.',
    historyEmpty: 'No tiers have fired yet.',
    dueLabel: (level: number) => `Level ${level}`,
  },
  notifications: {
    bellLabel: 'Notifications',
    unreadBadgeLabel: (count: number) => `${count} unread notification${count === 1 ? '' : 's'}`,
    drawerTitle: 'Notifications',
    drawerEmpty: 'No notifications yet.',
    viewAll: 'View all',
    pageTitle: 'Notifications',
    pageDescription: 'Escalation notifications you were sent, most recent first.',
    loadError: 'Could not load notifications.',
    emptyTitle: 'No notifications',
    emptyBody: "You'll be notified here when an incident you can see escalates.",
    lastUpdated: (relative: string) => `Last updated ${relative}`,
    updateFailed: 'Could not refresh — showing the last known state.',
  },
  timeline: {
    timelineTab: 'Timeline',
    loadError: 'Could not load the timeline.',
    loadMore: 'Load more history',
    emptyTitle: 'Nothing recorded yet',
    emptyBody: 'Every stage change, severity change, and note lands here as it happens.',
    redactedNote: 'Investigation note added · restricted',
    exactTimestampLabel: (timestamp: string) => `Exactly ${timestamp}`,
  },
  admin: {
    auditLogTitle: 'Audit log',
    auditLogDescription: 'Every recorded event across every incident, searchable by type, actor, incident, or date.',
    loadAuditError: 'Could not load the audit log.',
    auditEmptyTitle: 'No matching events',
    auditEmptyBody: 'Try widening the filters above.',
    auditFilterType: 'Event type',
    auditFilterTypeAny: 'Any type',
    auditFilterActor: 'Actor ID',
    auditFilterActorPlaceholder: 'Paste a user id…',
    auditFilterIncident: 'Incident ID',
    auditFilterIncidentPlaceholder: 'Paste an incident id…',
    auditClearFilters: 'Clear all',
    auditColumns: {
      occurredAt: 'When',
      type: 'Event',
      actor: 'Actor',
      incident: 'Incident',
      fromTo: 'From → To',
      reason: 'Reason',
    },
    usersPageTitle: 'Users',
    usersPageDescription: 'Manage roles, clearance levels, and account status.',
    loadUsersError: 'Could not load users.',
    usersEmptyTitle: 'No matching users',
    usersEmptyBody: 'Try widening the filters above.',
    usersFilterRole: 'Role',
    usersFilterRoleAny: 'Any role',
    usersFilterStatus: 'Status',
    usersFilterStatusAny: 'Any status',
    usersFilterStatusActive: 'Active',
    usersFilterStatusInactive: 'Inactive',
    usersFilterSearch: 'Search',
    usersFilterSearchPlaceholder: 'Name or email…',
    usersColumns: {
      user: 'User',
      role: 'Role',
      clearance: 'Clearance',
      status: 'Status',
      createdAt: 'Created',
    },
    statusActive: 'Active',
    statusInactive: 'Inactive',
    editUserDrawerTitle: (displayName: string) => `Edit ${displayName}`,
    roleLabel: 'Role',
    clearanceLabel: 'Clearance level',
    statusLabel: 'Account status',
    saveRole: 'Save role',
    saveClearance: 'Save clearance',
    activateUser: 'Activate',
    deactivateUser: 'Deactivate',
    selfModificationForbidden: 'You cannot change your own role or clearance level.',
    lastAdminError: 'The last active administrator cannot be demoted or deactivated.',
    roleChangedToast: 'Role updated.',
    clearanceChangedToast: (affectedIncidentCount: number) =>
      affectedIncidentCount > 0
        ? `Clearance updated — ${affectedIncidentCount} incident(s) were unassigned and returned to Triage.`
        : 'Clearance updated.',
    statusChangedToast: (isActive: boolean) => (isActive ? 'User activated.' : 'User deactivated.'),
    clearanceImpactDialogTitle: 'Confirm clearance change',
    clearanceImpactLoading: 'Checking affected incidents…',
    clearanceImpactNone: 'No incidents will be affected by this change.',
    clearanceImpactWarning: (count: number) =>
      `${count} incident${count === 1 ? '' : 's'} currently assigned to this user will be unassigned and returned to Triage:`,
    clearanceImpactConfirm: 'Confirm change',
    escalationPolicyTitle: 'Escalation Policy',
    escalationPolicyDescription: 'Configure the escalation tiers used by the automated escalation job.',
    loadTiersError: 'Could not load escalation tiers.',
    tierColumns: {
      severity: 'Severity',
      level: 'Level',
      thresholdMinutes: 'Threshold (minutes)',
    },
    saveAllTiers: 'Save all',
    tiersSavedToast: 'Escalation tiers updated.',
    tierPreview: (severity: string, thresholds: readonly number[]) =>
      `A ${severity} incident will escalate at ${thresholds.map((m) => `${m}m`).join(', ')}.`,
    tierSaveDisabledReason: 'Fix the highlighted tiers before saving.',
    jobDiagnosticsTitle: 'Job Diagnostics',
    jobDiagnosticsDescription: 'Recent escalation job runs, and a manual trigger for testing.',
    loadJobRunsError: 'Could not load job runs.',
    jobRunsEmptyTitle: 'The escalation job has not run yet',
    jobRunsEmptyBody: 'It runs automatically on the configured interval, or you can trigger it manually below.',
    jobRunColumns: {
      startedAt: 'Started',
      outcome: 'Outcome',
      scanned: 'Scanned',
      escalated: 'Escalated',
      notified: 'Notified',
      duration: 'Duration',
    },
    runJobNow: 'Run now',
    runJobToast: (outcome: string) => `Job run finished: ${outcome.replaceAll('_', ' ').toLowerCase()}.`,
  },
  analytics: {
    pageTitle: 'Analytics',
    pageDescription: 'Incident counts and escalation performance for the selected period.',
    clearanceScopeNotice: (clearanceLevel: number) =>
      `These figures include only incidents at or below your clearance level (${clearanceLevel}). Other viewers may legitimately see different totals for the same period.`,
    presetLabel: 'Period',
    preset7d: 'Last 7 days',
    preset30d: 'Last 30 days',
    preset90d: 'Last 90 days',
    presetQuarter: 'This quarter',
    presetCustom: 'Custom',
    bucketLabel: 'Group by',
    bucketDay: 'Day',
    bucketWeek: 'Week',
    bucketMonth: 'Month',
    kpiTotal: 'Total incidents',
    kpiOpen: 'Open',
    kpiEscalated: 'Escalated',
    kpiMedianAck: 'Median time to acknowledge',
    kpiNoData: '—',
    loadOverviewError: 'Could not load the analytics overview.',
    matrixTitle: 'Incidents by type and severity',
    matrixLoadError: 'Could not load the type/severity matrix.',
    matrixEmptyTitle: 'No incidents in this period',
    matrixEmptyBody: 'Try widening the period above.',
    matrixWidenAction: 'Widen to 90 days',
    matrixRowTotal: 'Total',
    matrixColumnTotal: 'Total',
    trendTitle: 'Trend',
    trendLoadError: 'Could not load the trend chart.',
    trendEmptyTitle: 'Nothing to chart yet',
    trendEmptyBody: 'No incidents were created in this period.',
    escalationPerformanceTitle: 'Escalation performance',
    escalationPerformanceDescription: 'Median and 90th-percentile time to acknowledge, by severity, for incidents that escalated in this period.',
    escalationPerformanceLoadError: 'Could not load escalation performance.',
    escalationPerformanceEmpty: 'No incidents escalated in this period.',
    escalationPerformanceForbidden: 'Visible to Triage Managers and Admins only.',
    escalationColumns: {
      severity: 'Severity',
      escalatedCount: 'Escalated',
      acknowledgedCount: 'Acknowledged',
      medianAck: 'Median ack',
      p90Ack: 'P90 ack',
    },
    exportCsv: 'Export CSV',
    exportingCsv: 'Exporting…',
    exportError: 'Could not export the CSV.',
    invalidPeriodToast: 'The requested period was invalid — showing the default period instead.',
  },
} as const;
