import { ROUTES } from '../app/routes';

const STATIC_ROUTE_PATHS: readonly string[] = (Object.values(ROUTES) as readonly unknown[]).filter(
  (value): value is string => typeof value === 'string',
);

/** Route prefixes generated by a ROUTES function (e.g. `incidentDetail(id)`), listed
 * here since a redirect target arrives as a raw string, not a call we can compare. */
const DYNAMIC_ROUTE_PREFIXES: readonly string[] = ['/incidents/'];

/**
 * Validates a `?next=` query param before it's ever passed to `navigate()`. A bare
 * `startsWith('/')` check is not enough: `//evil.com` also starts with `/` but browsers
 * and React Router treat a leading `//` as protocol-relative, i.e. an off-app redirect
 * (security.md — "validated against ROUTES before navigate(), never passed straight
 * through, or the app becomes an open redirect").
 */
export function resolvePostLoginRedirect(next: string | null, fallback: string): string {
  if (!next || !next.startsWith('/') || next.startsWith('//') || next.includes('\\')) {
    return fallback;
  }
  const [pathOnly = ''] = next.split(/[?#]/);
  const isKnownRoute =
    STATIC_ROUTE_PATHS.includes(pathOnly) || DYNAMIC_ROUTE_PREFIXES.some((prefix) => pathOnly.startsWith(prefix));
  return isKnownRoute ? next : fallback;
}
