export const ADMIN = {
  auditLogTitle: 'Audit log',
  auditLogDescription: 'Every recorded event across every incident, searchable by type, actor, incident, or date.',
  loadAuditError: 'Could not load the audit log.',
  auditEmptyTitle: 'No matching events',
  auditEmptyBody: 'Try widening the filters above.',
  auditFilterType: 'Event type',
  auditFilterTypeAny: 'Any type',
  auditFilterActor: 'Actor ID',
  auditFilterActorPlaceholder: 'Paste a user id…',
  auditFilterIncident: 'Incident ID',
  auditFilterIncidentPlaceholder: 'Paste an incident id…',
  auditClearFilters: 'Clear all',
  auditColumns: {
    occurredAt: 'When',
    type: 'Event',
    actor: 'Actor',
    incident: 'Incident',
    fromTo: 'From → To',
    reason: 'Reason',
  },
  usersPageTitle: 'Users',
  usersPageDescription: 'Manage roles, clearance levels, and account status.',
  loadUsersError: 'Could not load users.',
  usersEmptyTitle: 'No matching users',
  usersEmptyBody: 'Try widening the filters above.',
  usersFilterRole: 'Role',
  usersFilterRoleAny: 'Any role',
  usersFilterStatus: 'Status',
  usersFilterStatusAny: 'Any status',
  usersFilterStatusActive: 'Active',
  usersFilterStatusInactive: 'Inactive',
  usersFilterSearch: 'Search',
  usersFilterSearchPlaceholder: 'Name or email…',
  usersColumns: {
    user: 'User',
    role: 'Role',
    clearance: 'Clearance',
    status: 'Status',
    createdAt: 'Created',
  },
  statusActive: 'Active',
  statusInactive: 'Inactive',
  editUserDrawerTitle: (displayName: string) => `Edit ${displayName}`,
  roleLabel: 'Role',
  clearanceLabel: 'Clearance level',
  statusLabel: 'Account status',
  saveRole: 'Save role',
  saveClearance: 'Save clearance',
  activateUser: 'Activate',
  deactivateUser: 'Deactivate',
  selfModificationForbidden: 'You cannot change your own role or clearance level.',
  lastAdminError: 'The last active administrator cannot be demoted or deactivated.',
  roleChangedToast: 'Role updated.',
  clearanceChangedToast: (affectedIncidentCount: number) =>
    affectedIncidentCount > 0
      ? `Clearance updated — ${affectedIncidentCount} incident(s) were unassigned and returned to Triage.`
      : 'Clearance updated.',
  statusChangedToast: (isActive: boolean) => (isActive ? 'User activated.' : 'User deactivated.'),
  clearanceImpactDialogTitle: 'Confirm clearance change',
  clearanceImpactLoading: 'Checking affected incidents…',
  clearanceImpactNone: 'No incidents will be affected by this change.',
  clearanceImpactWarning: (count: number) =>
    `${count} incident${count === 1 ? '' : 's'} currently assigned to this user will be unassigned and returned to Triage:`,
  clearanceImpactConfirm: 'Confirm change',
  escalationPolicyTitle: 'Escalation Policy',
  escalationPolicyDescription: 'Configure the escalation tiers used by the automated escalation job.',
  loadTiersError: 'Could not load escalation tiers.',
  tierColumns: {
    severity: 'Severity',
    level: 'Level',
    thresholdMinutes: 'Threshold (minutes)',
  },
  saveAllTiers: 'Save all',
  tiersSavedToast: 'Escalation tiers updated.',
  tierPreview: (severity: string, thresholds: readonly number[]) =>
    `A ${severity} incident will escalate at ${thresholds.map((m) => `${m}m`).join(', ')}.`,
  tierSaveDisabledReason: 'Fix the highlighted tiers before saving.',
  jobDiagnosticsTitle: 'Job Diagnostics',
  jobDiagnosticsDescription: 'Recent escalation job runs, and a manual trigger for testing.',
  loadJobRunsError: 'Could not load job runs.',
  jobRunsEmptyTitle: 'The escalation job has not run yet',
  jobRunsEmptyBody: 'It runs automatically on the configured interval, or you can trigger it manually below.',
  jobRunColumns: {
    startedAt: 'Started',
    outcome: 'Outcome',
    scanned: 'Scanned',
    escalated: 'Escalated',
    notified: 'Notified',
    duration: 'Duration',
  },
  runJobNow: 'Run now',
  runJobToast: (outcome: string) => `Job run finished: ${outcome.replaceAll('_', ' ').toLowerCase()}.`,
} as const;
