import type { AuditEventType, Role } from '../../api/contracts/enums';

const ROLE_LABEL: Readonly<Record<Role, string>> = {
  REPORTER: 'Reporter',
  TRIAGE_MANAGER: 'Triage manager',
  INVESTIGATOR: 'Investigator',
  ADMIN: 'Administrator',
};

const ROLE_DESCRIPTION: Readonly<Record<Role, string>> = {
  REPORTER: 'Can report incidents and follow the ones they reported.',
  TRIAGE_MANAGER: 'Reviews new reports, sets severity and assigns investigators.',
  INVESTIGATOR: 'Works assigned incidents through investigation and closure.',
  ADMIN: 'Manages users, escalation policy and system diagnostics.',
};

const AUDIT_EVENT_LABEL: Readonly<Record<AuditEventType, string>> = {
  INCIDENT_CREATED: 'Incident created',
  STAGE_CHANGED: 'Stage changed',
  SEVERITY_CHANGED: 'Severity changed',
  INVESTIGATOR_ASSIGNED: 'Investigator assigned',
  INVESTIGATOR_UNASSIGNED: 'Investigator unassigned',
  INCIDENT_ACKNOWLEDGED: 'Acknowledged',
  NOTE_ADDED: 'Note added',
  CLOSURE_PROPOSED: 'Closure proposed',
  CLOSURE_APPROVED: 'Closure approved',
  CLOSURE_REJECTED: 'Closure rejected',
  INCIDENT_ESCALATED: 'Escalated',
  ACCESS_DENIED: 'Access denied',
  USER_CLEARANCE_CHANGED: 'Clearance changed',
  USER_ROLE_CHANGED: 'Role changed',
};

/** Clearance N lets a user see incidents up to severity rank N. */
const CLEARANCE_DESCRIPTION: Readonly<Record<number, string>> = {
  1: 'Sees Low severity incidents only.',
  2: 'Sees incidents up to Medium severity.',
  3: 'Sees incidents up to High severity.',
  4: 'Sees every incident, including Critical.',
};

const JOB_OUTCOME_LABEL = {
  COMPLETED: 'Completed',
  SKIPPED_LOCKED: 'Skipped (locked)',
  FAILED: 'Failed',
} as const;

export const ADMIN = {
  cancel: 'Cancel',
  clearFilters: 'Clear filters',
  // ── Audit log ───────────────────────────────────────────────────────────────
  auditLogTitle: 'Audit log',
  auditLogDescription: 'Every recorded event across every incident, searchable by type, actor, incident, or date.',
  loadAuditError: 'Could not load the audit log.',
  auditEmptyTitle: 'No matching events',
  auditEmptyBody: 'Try a different view, or widen the filters.',
  auditTotal: (count: number) => `${count.toLocaleString('en')} event${count === 1 ? '' : 's'}`,
  auditViewsLabel: 'Event view',
  auditViewAll: 'All events',
  auditGroups: {
    lifecycle: 'Incident lifecycle',
    assignment: 'Assignment & notes',
    closure: 'Closure',
    access: 'Access & users',
  },
  auditFiltersTitle: 'Filter the audit log',
  auditFilterTypeHint: 'Pick any — none means all',
  auditFilterDates: 'Occurred between',
  auditEmptyUnfilteredBody: 'Events appear here as soon as anyone acts on an incident.',
  auditFilterType: 'Event types',
  auditFilterTypeAny: 'Any type',
  auditFilterActor: 'Actor ID',
  auditFilterActorPlaceholder: 'e.g. ckx9a1b2c3…',
  auditFilterActorHint: 'The exact user ID of whoever performed the action.',
  auditFilterIncident: 'Incident ID',
  auditFilterIncidentPlaceholder: 'e.g. ckx7d4e5f6…',
  auditFilterIncidentHint: 'The internal incident ID, not the INC- reference.',
  auditClearFilters: 'Clear all',
  auditEventLabel: (type: AuditEventType): string => AUDIT_EVENT_LABEL[type],
  auditSystemActor: 'System',
  auditShowFullReason: 'Show full reason',
  auditShowLessReason: 'Show less',
  auditColumns: {
    occurredAt: 'When',
    type: 'Event',
    actor: 'Actor',
    incident: 'Incident',
    fromTo: 'From → To',
    reason: 'Reason',
  },
  auditChip: {
    type: (label: string) => `Type: ${label}`,
    group: (label: string) => `Events: ${label}`,
    actor: (id: string) => `Actor: ${id}`,
    incident: (id: string) => `Incident: ${id}`,
    from: (date: string) => `From ${date}`,
    to: (date: string) => `To ${date}`,
  },
  removeFilter: (label: string) => `Remove filter: ${label}`,
  // ── Users ───────────────────────────────────────────────────────────────────
  usersPageTitle: 'Users',
  usersPageDescription: 'Manage roles, clearance levels, and account status.',
  usersTotal: (count: number) => `${count} user${count === 1 ? '' : 's'}`,
  loadUsersError: 'Could not load users.',
  usersEmptyTitle: 'No matching users',
  usersEmptyBody: 'Try widening the filters above.',
  usersFilterRole: 'Role',
  usersFilterRoleAny: 'Any role',
  usersFilterStatus: 'Status',
  usersFilterStatusAny: 'Any status',
  usersFilterStatusActive: 'Active',
  usersFilterStatusInactive: 'Inactive',
  usersFilterSearch: 'Search',
  usersFilterSearchPlaceholder: 'Name or email…',
  usersClearFilters: 'Clear all',
  usersChip: {
    role: (label: string) => `Role: ${label}`,
    status: (label: string) => `Status: ${label}`,
    search: (q: string) => `Search: “${q}”`,
  },
  usersColumns: {
    user: 'User',
    role: 'Role',
    clearance: 'Clearance',
    status: 'Status',
    createdAt: 'Created',
    actions: 'Actions',
  },
  editUser: 'Edit',
  editUserAria: (displayName: string) => `Edit ${displayName}`,
  roleLabelFor: (role: Role): string => ROLE_LABEL[role],
  roleDescription: (role: Role): string => ROLE_DESCRIPTION[role],
  clearanceLevelLabel: (level: number) => `Level ${level}`,
  clearanceLevelOption: (level: number) => `Level ${level} — ${CLEARANCE_DESCRIPTION[level] ?? ''}`,
  clearanceDescription: (level: number): string => CLEARANCE_DESCRIPTION[level] ?? '',
  statusActive: 'Active',
  statusInactive: 'Inactive',
  // ── Edit user drawer ────────────────────────────────────────────────────────
  editUserDrawerTitle: (displayName: string) => `Edit ${displayName}`,
  memberSince: (date: string) => `Member since ${date}`,
  roleSectionTitle: 'Role',
  clearanceSectionTitle: 'Clearance',
  roleLabel: 'Set role',
  clearanceLabel: 'Set clearance level',
  statusLabel: 'Account status',
  currentValue: (value: string) => `Current: ${value}`,
  unsavedBadge: 'Unsaved',
  roleUnchangedHint: 'Pick a different role to enable saving.',
  clearanceUnchangedHint: 'Pick a different level to enable saving.',
  clearanceLoweringHint: 'Lowering clearance shows the affected incidents before anything changes.',
  statusActiveDescription: 'This person can sign in and work incidents.',
  statusInactiveDescription: 'This person cannot sign in. Their history is kept.',
  saveRole: 'Save role',
  saveClearance: 'Save clearance',
  activateUser: 'Activate',
  deactivateUser: 'Deactivate',
  deactivateConfirmTitle: (displayName: string) => `Deactivate ${displayName}?`,
  deactivateConfirmBody: 'They will be signed out and unable to sign in until an administrator reactivates the account.',
  deactivateConfirmAction: 'Deactivate user',
  discardTitle: 'Discard changes?',
  discardBody: 'You have unsaved role or clearance changes. Closing now will lose them.',
  discardAction: 'Discard',
  selfModificationForbidden: 'You cannot change your own role or clearance level.',
  lastAdminError: 'The last active administrator cannot be demoted or deactivated.',
  roleChangedToast: 'Role updated.',
  clearanceChangedToast: (affectedIncidentCount: number) =>
    affectedIncidentCount > 0
      ? `Clearance updated — ${affectedIncidentCount} incident(s) were unassigned and returned to Triage.`
      : 'Clearance updated.',
  statusChangedToast: (isActive: boolean) => (isActive ? 'User activated.' : 'User deactivated.'),
  // ── Clearance impact dialog ─────────────────────────────────────────────────
  clearanceImpactDialogTitle: 'Confirm clearance change',
  clearanceImpactDescription: (from: number, to: number) => `Lowering clearance from Level ${from} to Level ${to}.`,
  clearanceImpactLoading: 'Checking affected incidents…',
  clearanceImpactError: 'We could not check which incidents this affects.',
  clearanceImpactNone: 'No incidents will be affected by this change.',
  clearanceImpactWarning: (count: number) =>
    `${count} incident${count === 1 ? '' : 's'} currently assigned to this user will be unassigned and returned to Triage:`,
  clearanceImpactConfirm: 'Confirm change',
  // ── Escalation policy ───────────────────────────────────────────────────────
  escalationPolicyTitle: 'Escalation Policy',
  escalationPolicyDescription: 'Configure the escalation tiers used by the automated escalation job.',
  loadTiersError: 'Could not load escalation tiers.',
  tierColumns: {
    severity: 'Severity',
    level: 'Level',
    thresholdMinutes: 'Threshold (minutes)',
  },
  tierLevelLabel: (level: number) => `Level ${level}`,
  tierMinutesSuffix: 'min',
  tierHumanHint: (formatted: string) => `= ${formatted} after the clock starts`,
  tierEdited: 'Edited',
  tierPreviewTitle: 'What this policy does',
  tierPreviewBody: 'Thresholds are measured from when an incident first reaches a high severity.',
  tierCount: (count: number) => `${count} tier${count === 1 ? '' : 's'}`,
  saveAllTiers: 'Save all',
  resetTiers: 'Reset',
  resetTiersTitle: 'Reset unsaved changes?',
  resetTiersBody: 'Every threshold goes back to the saved policy.',
  resetTiersAction: 'Reset changes',
  unsavedChanges: (count: number) => `${count} unsaved change${count === 1 ? '' : 's'}`,
  noUnsavedChanges: 'All changes saved',
  tiersSavedToast: 'Escalation tiers updated.',
  tierPreview: (severity: string, thresholds: readonly string[]) =>
    `A ${severity} incident will escalate at ${thresholds.join(', ')}.`,
  tierSaveDisabledReason: 'Fix the highlighted tiers before saving.',
  // ── Job diagnostics ─────────────────────────────────────────────────────────
  jobDiagnosticsTitle: 'Job Diagnostics',
  jobDiagnosticsDescription: 'Recent escalation job runs, and a manual trigger for testing.',
  loadJobRunsError: 'Could not load job runs.',
  jobRunsTableLabel: 'Escalation job runs',
  jobRunsEmptyTitle: 'The escalation job has not run yet',
  jobRunsEmptyBody: 'It runs automatically on the configured interval, or you can trigger it with Run now above.',
  jobRunColumns: {
    startedAt: 'Started',
    outcome: 'Outcome',
    scanned: 'Scanned',
    escalated: 'Escalated',
    notified: 'Notified',
    duration: 'Duration',
  },
  jobOutcomeLabel: (outcome: keyof typeof JOB_OUTCOME_LABEL): string => JOB_OUTCOME_LABEL[outcome],
  jobRunning: 'Running',
  jobDurationUnderSecond: '<1s',
  runJobNow: 'Run now',
  runJobToast: (outcome: string) => `Job run finished: ${outcome.replaceAll('_', ' ').toLowerCase()}.`,
} as const;
