export const ANALYTICS = {
  pageTitle: 'Analytics',
  pageDescription: 'Incident counts and escalation performance for the selected period.',
  clearanceScopeNotice: (clearanceLevel: number) =>
    `These figures include only incidents at or below your clearance level (${clearanceLevel}). Other viewers may legitimately see different totals for the same period.`,
  presetLabel: 'Period',
  preset7d: 'Last 7 days',
  preset30d: 'Last 30 days',
  preset90d: 'Last 90 days',
  presetQuarter: 'This quarter',
  presetCustom: 'Custom',
  bucketLabel: 'Group by',
  bucketDay: 'Day',
  bucketWeek: 'Week',
  bucketMonth: 'Month',
  kpiTotal: 'Total incidents',
  kpiOpen: 'Open',
  kpiEscalated: 'Escalated',
  kpiMedianAck: 'Median time to acknowledge',
  kpiNoData: '—',
  loadOverviewError: 'Could not load the analytics overview.',
  matrixTitle: 'Incidents by type and severity',
  matrixLoadError: 'Could not load the type/severity matrix.',
  matrixEmptyTitle: 'No incidents in this period',
  matrixEmptyBody: 'Try widening the period above.',
  matrixWidenAction: 'Widen to 90 days',
  matrixRowTotal: 'Total',
  matrixColumnTotal: 'Total',
  trendTitle: 'Trend',
  trendLoadError: 'Could not load the trend chart.',
  trendEmptyTitle: 'Nothing to chart yet',
  trendEmptyBody: 'No incidents were created in this period.',
  escalationPerformanceTitle: 'Escalation performance',
  escalationPerformanceDescription: 'Median and 90th-percentile time to acknowledge, by severity, for incidents that escalated in this period.',
  escalationPerformanceLoadError: 'Could not load escalation performance.',
  escalationPerformanceEmpty: 'No incidents escalated in this period.',
  escalationPerformanceForbidden: 'Visible to Triage Managers and Admins only.',
  escalationColumns: {
    severity: 'Severity',
    escalatedCount: 'Escalated',
    acknowledgedCount: 'Acknowledged',
    medianAck: 'Median ack',
    p90Ack: 'P90 ack',
  },
  exportCsv: 'Export CSV',
  exportingCsv: 'Exporting…',
  exportError: 'Could not export the CSV.',
  invalidPeriodToast: 'The requested period was invalid — showing the default period instead.',
} as const;
