export const ANALYTICS = {
  pageTitle: 'Analytics',
  pageDescription: 'Incident counts and escalation performance for the selected period.',
  clearanceScopeNotice: (clearanceLevel: number) =>
    `These figures include only incidents at or below your clearance level (${clearanceLevel}). Other viewers may legitimately see different totals for the same period.`,
  periodToolbarLabel: 'Reporting period',
  presetLabel: 'Period',
  preset7d: 'Last 7 days',
  preset30d: 'Last 30 days',
  preset90d: 'Last 90 days',
  presetQuarter: 'This quarter',
  presetCustom: 'Custom',
  presetShort7d: '7 days',
  presetShort30d: '30 days',
  presetShort90d: '90 days',
  presetShortQuarter: 'Quarter',
  periodSummary: (days: number, bucket: string) => `${days} day${days === 1 ? '' : 's'} · trend grouped by ${bucket}`,
  filtersTitle: 'Refine analytics',
  filtersReset: 'Reset',
  customRangeLabel: 'Custom range',
  rangeDays: (days: number) => `${days} day${days === 1 ? '' : 's'}`,
  rangeIncomplete: 'Pick both a start and an end date.',
  rangeReversed: 'The end date is before the start date.',
  rangeTooWide: (maxDays: number) => `Pick a range of ${maxDays} days or fewer.`,
  bucketHint: 'Trend chart only',
  multiSelectHint: 'Pick any — none means all',
  typeFilterLabel: 'Incident type',
  stageFilterLabel: 'Stage',
  chipType: (type: string) => `Type: ${type}`,
  chipStage: (stage: string) => `Stage: ${stage}`,
  kpiShareOfTotal: (percent: number) => `${percent}% of total`,
  kpiInPeriod: 'created in this period',
  kpiAcknowledgedOnly: 'acknowledged incidents only',
  bucketLabel: 'Group by',
  bucketDay: 'Day',
  bucketWeek: 'Week',
  bucketMonth: 'Month',
  kpiTotal: 'Total incidents',
  kpiOpen: 'Open',
  kpiEscalated: 'Escalated',
  kpiMedianAck: 'Median time to acknowledge',
  kpiHints: {
    total: 'Every incident created in the selected period that your clearance lets you see.',
    open: 'Incidents from this period that are not yet closed.',
    escalated: 'Incidents from this period that crossed at least one escalation tier before being acknowledged.',
    medianAck: 'Half of the acknowledged incidents in this period were acknowledged faster than this.',
  },
  kpiInfoLabel: (metric: string) => `About ${metric}`,
  kpiNoData: '—',
  loadOverviewError: 'Could not load the analytics overview.',
  matrixTitle: 'Incidents by type and severity',
  matrixDescription: 'Select a count to open the matching incidents.',
  matrixTypeColumn: 'Type',
  matrixCellLabel: (count: number, type: string, severity: string) =>
    `${count} ${type} incidents at ${severity} severity — view list`,
  matrixLegendLabel: 'Shading is relative within each severity column',
  matrixLegendFewer: 'Fewer',
  matrixLegendMore: 'More',
  matrixLoadError: 'Could not load the type/severity matrix.',
  matrixEmptyTitle: 'No incidents in this period',
  matrixEmptyBody: 'Try widening the period above.',
  matrixWidenAction: 'Widen to 90 days',
  matrixRowTotal: 'Total',
  matrixColumnTotal: 'Total',
  trendTitle: 'Trend',
  trendDescription: 'Incidents created per period, stacked by severity.',
  trendSummary: (periods: number, severities: number, peak: number) =>
    `Trend chart: ${periods} periods, ${severities} severities, peak ${peak} incidents in one period.`,
  trendLegendLabel: 'Severity legend',
  trendLoading: 'Loading the trend chart…',
  trendLoadError: 'Could not load the trend chart.',
  trendEmptyTitle: 'Nothing to chart yet',
  trendEmptyBody: 'No incidents were created in this period.',
  escalationPerformanceTitle: 'Escalation performance',
  escalationPerformanceDescription: 'Median and 90th-percentile time to acknowledge, by severity, for incidents that escalated in this period.',
  escalationPerformanceLoadError: 'Could not load escalation performance.',
  escalationPerformanceEmpty: 'No incidents escalated in this period.',
  escalationPerformanceEmptyBody: 'Nothing crossed an escalation tier unacknowledged. Try a wider period to compare.',
  escalationPerformanceForbidden: 'Visible to Triage Managers and Admins only.',
  escalationColumns: {
    severity: 'Severity',
    escalatedCount: 'Escalated',
    acknowledgedCount: 'Acknowledged',
    medianAck: 'Median ack',
    p90Ack: 'P90 ack',
  },
  exportCsv: 'Export CSV',
  exportingCsv: 'Exporting…',
  exportError: 'Could not export the CSV.',
  exportSuccessToast: 'CSV downloaded — check your downloads folder.',
  invalidPeriodToast: 'The requested period was invalid — showing the default period instead.',
} as const;
