export const DASHBOARD = {
  pageTitle: 'Dashboard',
  greeting: (name: string) => `Welcome back, ${name}`,
  description: "Here's what needs your attention.",
  loadSummaryError: 'Could not load the incident summary.',
  byStageTitle: 'Incidents by stage',
  quickLinksTitle: 'Quick links',
  reportIncident: 'Report incident',
  viewIncidents: 'View incidents',
  myReports: 'My reports',
  triageQueue: 'Triage queue',
  investigations: 'My investigations',
  pendingClosures: 'Pending closures',
  recentEscalationsTitle: 'Recent escalations',
  recentEscalationsDescription: 'Unacknowledged incidents past a tier threshold.',
  loadEscalationsError: 'Could not load recent escalations.',
  noEscalations: 'Nothing currently escalated.',
  viewAllEscalations: 'View all escalations',
} as const;
