export const DASHBOARD = {
  pageTitle: 'Dashboard',
  greeting: (name: string) => `Welcome back, ${name}`,
  description: "Here's what needs your attention.",
  heroEyebrow: 'Your workspace',
  heroChipsLabel: 'Your access',
  heroActionsLabel: 'Shortcuts',
  loadSummaryError: 'Could not load the incident summary.',
  byStageTitle: 'Incidents by stage',
  byStageDescription: 'Select a stage to open its incidents.',
  stageTotal: (count: number) => `${count} total`,
  stageTileLabel: (stage: string, count: number) =>
    `${stage}: ${count} incident${count === 1 ? '' : 's'} — view list`,
  quickLinksTitle: 'Quick links',
  quickLinksDescription: 'Jump straight into your everyday work.',
  reportIncident: 'Report incident',
  viewIncidents: 'View incidents',
  myReports: 'My reports',
  triageQueue: 'Triage queue',
  investigations: 'My investigations',
  pendingClosures: 'Pending closures',
  adminLinksTitle: 'Administration',
  adminLinksDescription: 'Manage people, policy, and system health.',
  recentEscalationsTitle: 'Recent escalations',
  recentEscalationsDescription: 'Unacknowledged incidents past a tier threshold.',
  recentEscalationsEmptyBody: 'Every unacknowledged high-severity incident you can see is caught up.',
  loadEscalationsError: 'Could not load recent escalations.',
  noEscalations: 'Nothing currently escalated.',
  viewAllEscalations: 'View all escalations',
} as const;
