export const INCIDENTS = {
  submitReport: 'Submit report',
  viewIncident: 'View incident',
  reportAnother: 'Report another incident',
  incidentReported: 'Incident reported',
  notFoundTitle: 'Incident not found',
  notFoundBody: 'It may have been removed, or the link is incorrect.',
  backToList: 'Back to incident list',
  loadDetailError: 'Could not load this incident.',
  loadFormError: 'Could not load the report form.',
  reportPageTitle: 'Report Incident',
  reportTitle: 'Report an incident',
  reportDescription: 'Fill in what you know — invalid input is rejected before it reaches anyone.',
  reportAction: 'Report incident',
  reportSubmittedToast: (reference: string) => `Report ${reference} submitted.`,
  listTitle: 'Incidents',
  listDescription: 'Showing incidents at or below your clearance level.',
  loadListError: 'Could not load incidents.',
  myReportsTitle: 'My reports',
  myReportsDescription:
    "Incidents you reported that you can still see — a report filed above your clearance won't appear here (Q9).",
  loadMyReportsError: 'Could not load your reports.',
  noReportsYetTitle: 'No reports yet',
  noReportsYetBody: 'Incidents you file will show up here, as long as you can still see them.',
  clearanceHidesEverythingTitle: 'Your clearance hides everything here',
  clearanceHidesEverythingBody:
    'Every incident matching these filters is above your clearance level. An investigator or manager with higher clearance can still act on them.',
  noMatchTitle: 'No incidents match these filters',
  noMatchBody: 'Try widening the date range or clearing a filter.',
  clearAllFilters: 'Clear all filters',
  noIncidentsYetTitle: 'No incidents yet',
  noIncidentsYetBody: "Reports will show up here once they're filed.",
  aboveClearanceWarning: 'Above your clearance — you may not be able to view this report afterwards.',
  severityHelp: {
    LOW: 'Routine — visible to any staff member.',
    MEDIUM: 'Elevated — visible from clearance 2 up.',
    HIGH: 'Serious — starts the escalation clock; visible from clearance 3 up.',
    CRITICAL: 'Most severe — starts the escalation clock; visible to clearance 4 only.',
  },
  /** Enum value → readable type name ("DATA_PRIVACY" → "DATA PRIVACY"), for places
   * that only have the raw enum rather than the API's option label. */
  /** 'DATA_PRIVACY' -> 'Data Privacy'. Title case here, once, so selects, pills and
   * chips don't each shout the raw enum (or each re-case it their own way). */
  typeName: (value: string) =>
    value
      .toLowerCase()
      .split('_')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' '),
  columns: {
    reference: 'Reference',
    title: 'Title',
    type: 'Type',
    severity: 'Severity',
    stage: 'Stage',
    assignee: 'Assignee',
    age: 'Age',
    escalation: 'Escalation',
  },
  form: {
    typeLabel: 'Type',
    typePlaceholder: 'Select a type…',
    severityLabel: 'Severity',
    titleLabel: 'Title',
    titlePlaceholder: 'e.g. Water pooling by loading dock B',
    descriptionLabel: 'Description',
    descriptionPlaceholder: 'What happened, where and when, and who was involved or affected?',
    descriptionHint: 'At least 20 characters.',
    requiredNote: 'Fields marked * are required.',
    fixErrors: (count: number) => `Fix the ${count} highlighted field${count === 1 ? '' : 's'} to submit.`,
    imageLabel: 'Photo',
    imageHint: "A photo helps triage verify the report. If you don't have one, explain why below.",
    chooseImage: 'Choose photo…',
    replaceImage: 'Replace photo',
    removeImage: 'Remove photo',
    imagePreviewAlt: 'Selected incident photo',
    noImageReasonLabel: 'Why is there no photo?',
    noImageReasonPlaceholder: 'e.g. The hazard was cleared before I could take a photo.',
    noImageReasonHint: 'Required when no photo is attached — helps rule out fabricated reports.',
    errors: {
      typeRequired: 'Choose the type that best fits what happened.',
      severityRequired: 'Choose how severe the incident is.',
      titleTooShort: (min: number) => `Give the report a title of at least ${min} characters.`,
      titleTooLong: (max: number) => `Keep the title to ${max} characters or fewer.`,
      descriptionTooShort: (min: number) => `Describe what happened in at least ${min} characters.`,
      descriptionTooLong: (max: number) => `Keep the description to ${max} characters or fewer.`,
      imageTooLarge: 'Photos must be 10MB or smaller.',
      imageInvalidType: 'Choose a JPEG, PNG, WebP, or GIF image.',
      noImageReasonTooShort: (min: number) => `Explain why there's no photo in at least ${min} characters.`,
      noImageReasonTooLong: (max: number) => `Keep the explanation to ${max} characters or fewer.`,
    },
    sections: {
      what: { title: 'What happened', body: 'Pick the closest category — a triage manager can refine it later.' },
      severity: { title: 'How severe is it?', body: 'Severity decides who can see the report and whether the escalation clock starts.' },
      details: { title: 'Details', body: 'A short headline and a clear account help triage act quickly.' },
      evidence: {
        title: 'Photo evidence',
        body: "Attach a photo of what you saw, or explain why one isn't available — this helps rule out fabricated reports.",
      },
    },
  },
  receipt: {
    pageTitle: 'Report Submitted',
    title: 'Thanks — your report is in',
    body: 'Keep the reference below for any follow-up. A triage manager will pick it up from here.',
    referenceLabel: 'Reference',
    severityLabel: 'Filed as',
    nextStepsTitle: 'What happens next',
    nextSteps: [
      { id: 'triage', text: 'A triage manager reviews and acknowledges the report.' },
      { id: 'investigate', text: 'An investigator with the right clearance is assigned.' },
      { id: 'close', text: 'Findings and corrective actions are recorded before closure.' },
    ],
    viewMyReports: 'View my reports',
    noDetails: 'No submission details are available.',
  },
  copy: {
    copyReference: 'Copy reference',
    copied: 'Copied!',
    copyFailed: "Couldn't copy — select the reference and copy it manually.",
  },
  clearanceNotice: {
    title: 'You may not be able to view this report',
    body: 'This incident was filed at a severity above your clearance level. An investigator or manager can still act on it — keep the reference below if you need to follow up.',
  },
  detail: {
    fallbackTitle: 'Incident',
    documentTitle: (reference: string, title: string) => `${reference} · ${title}`,
    loading: 'Loading incident…',
    overviewTab: 'Overview',
    descriptionHeading: 'Description',
    resolutionHeading: 'Resolution',
    detailsHeading: 'Details',
    photoHeading: 'Photo',
    photoAlt: 'Photo attached to this incident report',
    noPhotoReasonHeading: "Why there's no photo",
    removedUser: 'someone since removed',
    progressLabel: 'Incident progress',
    stepState: {
      complete: 'completed',
      current: 'current stage',
      upcoming: 'not reached yet',
    },
    meta: {
      type: 'Type',
      reportedBy: 'Reported by',
      assignedInvestigator: 'Assigned investigator',
      unassigned: 'Unassigned',
      acknowledged: 'Acknowledged',
      acknowledgedValue: (at: string, by: string) => `${at} by ${by}`,
      notAcknowledged: 'Not yet acknowledged',
      escalation: 'Escalation',
      notEscalated: 'Not escalated',
      created: 'Created',
      lastUpdated: 'Last updated',
    },
  },
  timelineView: {
    listLabel: 'Incident history, newest first',
  },
} as const;
