export const NAV = {
  appTitle: 'Incident Reporting & Escalation',
  appShortTitle: 'Incident Desk',
  backToHome: 'Back to home',
  groups: {
    overview: 'Overview',
    report: 'Report',
    work: 'Work',
    monitor: 'Monitor',
    admin: 'Admin',
  },
  items: {
    dashboard: 'Dashboard',
    reportIncident: 'Report incident',
    incidents: 'Incidents',
    myReports: 'My reports',
    triageQueue: 'Triage queue',
    investigations: 'Investigations',
    pendingClosures: 'Pending closures',
    escalations: 'Escalations',
    analytics: 'Analytics',
    notifications: 'Notifications',
    users: 'Users',
    escalationPolicy: 'Escalation policy',
    jobDiagnostics: 'Job diagnostics',
    auditLog: 'Audit log',
  },
  skipToContent: 'Skip to main content',
  collapseSidebar: 'Collapse sidebar',
  expandSidebar: 'Expand sidebar',
  roleLabel: {
    REPORTER: 'Reporter',
    TRIAGE_MANAGER: 'Triage manager',
    INVESTIGATOR: 'Investigator',
    ADMIN: 'Administrator',
  },
  clearanceLevel: (level: number) => `Clearance level ${level}`,
} as const;

export const PALETTE = {
  trigger: 'Search…',
  shortcut: 'Ctrl K',
  triggerLabel: 'Open command palette',
  title: 'Command palette',
  description: 'Jump to a page or search incidents.',
  placeholder: 'Type a page name or search incidents…',
  empty: 'No matching pages.',
  pagesGroup: 'Go to',
  actionsGroup: 'Search',
  accountGroup: 'Account',
  searchIncidents: (query: string) => `Search incidents for “${query}”`,
  searchIncidentsHint: 'Search incidents by title or reference',
  logOut: 'Log out',
  loadingBar: 'Loading',
} as const;

export const FEEDBACK = {
  forbiddenTitle: "You don't have access to this page",
  forbiddenBody: "Your role doesn't permit this action. If you think this is a mistake, contact an administrator.",
  accessRevokedTitle: 'You no longer have access to this incident',
  accessRevokedBody:
    'Its severity was raised above your clearance level. This is expected — clearance is re-checked on every request.',
  notFoundTitle: "We couldn't find that page",
  notFoundBody: 'The link may be out of date, or the page may have moved. Check the address or head back to the dashboard.',
  unexpectedErrorTitle: 'Something went wrong',
  unexpectedErrorBody: 'The application hit an unexpected error. Reloading the page usually resolves it.',
  routeErrorTitle: "This page couldn't load",
  routeErrorBody: 'Something went wrong while showing this page. Try again — if it keeps happening, head back to the dashboard.',
  routeErrorDetails: 'Technical details',
  tryAgain: 'Try again',
  goToDashboard: 'Go to dashboard',
  reload: 'Reload',
} as const;

/** Copy introduced by the shadcn/ui migration — sr-only labels, dialog chrome, nav a11y strings. */
export const CHROME = {
  dialogClose: 'Close',
  sheetClose: 'Close',
  sideNavToggle: 'Toggle navigation',
  sideNavLabel: 'Main navigation',
  breadcrumbLabel: 'Breadcrumb',
  userMenuLabel: 'Account menu',
  paginationPrevious: 'Previous page',
  paginationNext: 'Next page',
  paginationSummary: (from: number, to: number, total: number) => `Showing ${from}–${to} of ${total}`,
  paginationLabel: 'Pagination',
  paginationPage: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
  paginationPreviousShort: 'Previous',
  paginationNextShort: 'Next',
  loading: 'Loading…',
  updating: 'Updating…',
  loadMore: 'Load more',
  retry: 'Retry',
  requestReference: (requestId: string) => `Reference: ${requestId}`,
  errorDefault: "We couldn't load this. Check your connection and try again.",
  dismiss: 'Dismiss',
  confirm: 'Confirm',
  cancel: 'Cancel',
  dateFrom: 'From',
  dateTo: 'To',
  escalatedLevel: (level: number) => `Escalated · L${level}`,
  characterCount: (count: number, max: number) => `${count} / ${max}`,
  characterCountShort: (remaining: number) => `${remaining} more to go`,
  overLimit: 'Over the limit',
  lastUpdated: (relative: string) => `Updated ${relative}`,
  autoRefreshing: 'Auto-refreshing',
  refreshNow: 'Refresh now',
} as const;
