export const TRIAGE = {
  queueTitle: 'Triage queue',
  queueDescription: 'Unacknowledged and new incidents at or below your clearance, most escalated first.',
  loadQueueError: 'Could not load the triage queue.',
  queueEmptyTitle: 'Nothing waiting on triage',
  queueEmptyBody: 'Every incident you can see is either acknowledged or past the triage stage.',
  viewFullList: 'View the full incident list',
  triageAction: 'Move to triage',
  acknowledge: 'Acknowledge',
  acknowledged: 'Acknowledged',
  changeSeverity: 'Change severity',
  assign: 'Assign investigator',
  reassign: 'Reassign investigator',
  unassign: 'Unassign',
  changeSeverityModalTitle: 'Change severity',
  reasonLabel: 'Reason',
  reasonHint: 'At least 10 characters — this is recorded on the incident’s audit trail.',
  assignDrawerTitle: 'Assign investigator',
  noEligibleInvestigators: (minClearance: number) => `No investigator has clearance ${minClearance} or above.`,
  hiddenInvestigatorsFootnote: (hidden: number) =>
    hidden === 1
      ? '1 investigator is hidden — their clearance is below this incident’s severity.'
      : `${hidden} investigators are hidden — their clearance is below this incident’s severity.`,
  unassignConfirmTitle: 'Unassign investigator?',
  unassignConfirmBody: 'This returns the incident to Triage. The investigator keeps no further access to it.',
  triagedToast: 'Moved to triage.',
  severityChangedToast: 'Severity updated.',
  assignedToast: 'Investigator assigned.',
  unassignedToast: 'Investigator unassigned.',
  acknowledgedToast: 'Incident acknowledged.',
  selfInflictedRaiseToast: 'Severity updated — you may lose access to this incident.',
  staleVersionError: 'This incident changed while you were viewing it. Refreshing…',
  actionsHeading: 'Actions',
  actionsRegionLabel: 'Incident actions',
  assignDrawerDescription: 'Only investigators whose clearance covers this incident’s severity are listed.',
  noEligibleInvestigatorsTitle: 'No eligible investigators',
  clearanceBadge: (level: number) => `Clearance ${level}`,
  changeSeverityModalDescription: 'The change and your reason are recorded on the incident’s audit trail.',
  severityCurrent: 'Current',
  severityNext: 'New',
  severityChangePreview: 'Severity change',
  impactWarningTitle: 'The assigned investigator will lose access',
  impactWarningBody:
    ' will be unassigned and this incident will return to Triage — their clearance doesn’t cover this severity.',
} as const;

export const INVESTIGATION = {
  myInvestigationsTitle: 'My investigations',
  myInvestigationsDescription: 'Incidents assigned to you that you can still see.',
  loadMyInvestigationsError: 'Could not load your investigations.',
  noInvestigationsTitle: 'No investigations assigned',
  noInvestigationsBody: 'Incidents assigned to you will show up here.',
  notesTab: 'Notes',
  confidentialityBanner: 'Visible only to you and administrators.',
  noNotesYetTitle: 'No investigation notes yet',
  noNotesYetBody: 'Notes you and other investigators add will appear here, newest first.',
  loadNotesError: 'Could not load investigation notes.',
  loadMoreNotes: 'Load more notes',
  composerLabel: 'Add a note',
  composerPlaceholder: 'Record what you found, who you spoke to, or what happens next…',
  composerCharacterCount: (count: number, max: number) => `${count} / ${max}`,
  addNote: 'Add note',
  addNoteToast: 'Note added.',
  restrictedClearanceTitle: 'Notes require higher clearance',
  restrictedClearanceBody: 'Your clearance no longer covers this incident, so its investigation notes are hidden too.',
  restrictedNotAssignedTitle: 'Notes are limited to the assigned investigator',
  restrictedNotAssignedBody:
    'Only the assigned investigator and administrators can read or add investigation notes — a triage role alone is not enough.',
  notesClosedNotice: 'This incident is closed. Notes can no longer be added, but existing notes are preserved above.',
  noInvestigationsAction: 'View the full incident list',
  sendingNote: 'Sending…',
  composerShortcutHint: 'Ctrl + Enter to add',
  notesListLabel: 'Investigation notes',
} as const;

export const CLOSURE = {
  closureTab: 'Closure',
  requirementsHint: 'At least 20 characters each — this is what stops closure through the API, not just this form.',
  rootCauseLabel: 'Root cause',
  rootCausePlaceholder: 'What actually caused this incident?',
  correctiveActionLabel: 'Corrective action',
  correctiveActionPlaceholder: 'What was done, or will be done, to prevent a recurrence?',
  proposeAction: 'Propose closure',
  proposeConfirmTitle: 'Propose closure?',
  proposeConfirmBody: 'This moves the incident to Pending Closure for a manager to review.',
  proposedToast: 'Closure proposed — awaiting manager review.',
  reviewTitle: 'Closure review',
  reviewDescription: 'Read the proposed root cause and corrective action, then approve or request changes.',
  approveAction: 'Approve',
  approveConfirmTitle: 'Approve closure?',
  approveConfirmBody: 'This closes the incident. A closed incident cannot be reopened or modified.',
  approvedToast: 'Incident closed.',
  requestChangesAction: 'Request changes',
  rejectModalTitle: 'Request changes',
  rejectReasonLabel: 'What needs to change?',
  rejectReasonHint: 'At least 10 characters — this is recorded on the incident’s audit trail and shown to the investigator.',
  rejectedToast: 'Sent back for changes.',
  closedBanner: (closedAt: string, closedBy: string) => `Closed on ${closedAt} by ${closedBy}`,
  pendingQueueTitle: 'Pending closures',
  pendingQueueDescription: 'Proposed closures awaiting your approval, at or below your clearance.',
  loadPendingQueueError: 'Could not load pending closures.',
  pendingQueueEmptyTitle: 'Nothing awaiting closure review',
  pendingQueueEmptyBody: 'Proposed closures you can see will show up here.',
  pendingQueueEmptyAction: 'View the full incident list',
  proposedColumn: 'Proposed',
  idleTitle: 'No closure has been proposed for this incident yet',
  idleBody: 'The assigned investigator proposes closure once the root cause and corrective action are known.',
  formTitle: 'Closure proposal',
  formDescription:
    'Explain what caused this incident and how a recurrence is prevented. A manager reviews it before the incident closes.',
  overLimitWarning: (max: number) => `Shorten the highlighted field to ${max} characters or fewer to continue.`,
  awaitingReview: 'Awaiting manager review',
  rejectModalDescription:
    'The incident returns to Investigation with its proposed text kept, so the investigator can revise it.',
  summaryTitle: 'Closure record',
  summaryDescription: 'Permanent and read-only — a closed incident cannot be reopened or modified.',
} as const;
